version: "3.8"

services:
  subnautica:
    build: .
    container_name: nitrox
    env_file:
      - secrets.env
    ports:
      - "11000:11000"
    volumes:
      - ./world:/server/world
      - ./server.cfg:/server/server.cfg
      - subnautica_content:/game/subnautica
      - steamcmd_login_volume:/steam/Steam
      
volumes:
  steamcmd_login_volume:
  subnautica_content:
